version: "3"

services:
  api:
    container_name: Backend
    build:
      context: ./src/api
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - shop-2025
    volumes:
      - ./src/api:/api
      - ./src/api/images:/api/images
    expose:
      - "5173"
  nginx:
    image: nginx:stable
    build: 
      context: ./containres/nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "${BACKEND_PORT}:5173"
    depends_on:
      - api
    networks:
      - shop-2025
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./logs/nginx/:/var/log/nginx
    extra_hosts:
      - host.docker.internal:host-gateway
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-2025
  elasticsearch:
    image: elasticsearch:8.16.4
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    env_file:
      - .env
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - shop-2025

volumes:
  postgres_data:
  es-data:


networks:
  shop-2025:
    driver: bridge