version: "3"

services:
  api:
    container_name: Backend
    build:
      context: .
      dockerfile: /src/api/Dockerfile
    env_file:
      - .env
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:3000"
    networks:
      - shop-2025
  
  frontend:
    build:
      context: .
      dockerfile: ./src/nuxt/Dockerfile
    env_file:
      - .env
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:5173"
    networks:
      - shop-2025
  nginx:
    image: nginx:stable
    build: 
      context: .
      dockerfile: /containres/nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - shop-2025

networks:
  shop-2025:
    driver: bridge