version: "3"

services:
  api:
    container_name: Backend
    build:
      context: ./src/api
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:5173"
    networks:
      - shop-2025
    volumes:
      - ./src/api:/api
  
#  frontend:
#    build:
#      context: .
#      dockerfile: ./src/nuxt/Dockerfile
#    env_file:
#      - .env
#    environment:
#      FRONTEND_PORT: ${FRONTEND_PORT}
#    ports:
#      - "${FRONTEND_PORT}:3000"
#    networks:
#      - shop-2025
  nginx:
    image: nginx:stable
    build: 
      context: ./containres/nginx
    env_file:
      - .env
    ports:
      - "8080:80"
#      - "${BACKEND_PORT}:5173"
    depends_on:
      - api
#      - frontend
    networks:
      - shop-2025
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./logs/nginx/:/var/log/nginx

networks:
  shop-2025:
    driver: bridge