version: "3"

services:
  api:
    container_name: Backend
    build:
      context: ./src/api
    env_file:
      - .env
    environment:
      - DB_HOST=${APP_DB_HOST}
      - DB_USER=${APP_DB_USER}
      - DB_PASSWORD=${APP_DB_PASSWORD}
      - DB_NAME=${APP_DB_NAME}
      - DB_PORT=${APP_DB_PORT}
      - ELASTIC_URL=${ELASTIC_URL}
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - shop-2025
    volumes:
      - ./src/api:/api
      - ./src/api/images:/api/images
    expose:
      - "5173"

  nginx:
    image: nginx:stable
    build: 
      context: ./containers/nginx
    env_file:
      - .env
    ports:
      - "80:80"
      - "${BACKEND_PORT}:5173"
    depends_on:
      - api
    networks:
      - shop-2025
    volumes:
      - /etc/localtime:/etc/localtime/:ro
      - ./logs/nginx/:/var/log/nginx
    extra_hosts:
      - host.docker.internal:host-gateway

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
    command:
      - start-dev
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - app-db
      - keycloak-db
    networks:
      - shop-2025

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_NAME}
    ports:
      - "${KC_DB_PORT}:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - shop-2025

  app-db:
    image: postgres:latest
    container_name: app-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
    ports:
      - "${APP_DB_PORT}:5432"
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - shop-2025

  elasticsearch:
    image: elasticsearch:8.16.4
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    env_file:
      - .env
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - shop-2025

volumes:
  app_db_data:
  keycloak_db_data:
  es-data:


networks:
  shop-2025:
    driver: bridge