version: "3"

services:
  api:
    container_name: Backend
    build:
      context: .
      dockerfile: /src/api/Dockerfile
    env_file:
      - .env
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:3000"

