export default {
  label: {
    name: 'Название',
    image: 'Изображения',
    parentSection: 'Родительский отдел',
    price: 'Цена',
    color: 'Цвет',
    description: 'Описание',
    section: 'Раздел',
    showOnMain: 'Выводить на главную страницу',
    mainSlider: 'Выводить в слайдер',
    save: 'Сохранить',
    cancel: 'Отмена',
    optionSection: 'Раздел',
    optionProduct: 'Продукт',
    countColumn: 'На странице',
    type: 'Тип',
    search: 'Поиск',
    clear: 'Очистить',
    reindex: 'Переиндексировать',
    add: 'Добавить',
    result: 'Результатов:',
    from: 'из',
  },
  title: {
    formEdit: 'Редактирование',
    formAdd: 'Новая запись',
    header: 'Администрирование',
  },
  hint: {
    price: 'Пример: 123',
  },
};
